services:
  devbox:
    build:
      context: .
      dockerfile: Containerfile
    container_name: devbox
    volumes:
    # ssh
      - ${HOME}/.ssh/devbox_ed25519.pub:/run/devbox_authorized_key:ro
    # shared dir
      - ${HOME}/devbox-share:/share
    ports:
      - "127.0.0.1:2200:22" # only at localhost for now
    restart: unless-stopped
